<?php
/**
 * Created by PhpStorm.
 * User: evolution
 * Date: 17-5-25
 * Time: 下午6:12
 */

namespace Evolution\WheelTimer\worker;


class ShareData extends \Threaded
{
    public $a;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}